name: .NET Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI Integration:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore ParabankTestAutomation.slnx
      
    - name: Build
      run: dotnet build ParabankTestAutomation.slnx --configuration Release --no-restore

    - name: Install Playwright Browsers
      run: dotnet playwright install
      working-directory: .

    - name: Run tests
      run: dotnet test ParabankTestAutomation.slnx --no-build --logger:"trx"
      continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'

     - name: Upload Playwright HTML Report and Screenshots
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          **/TestResults/
          **/traces/
          **/Logs/
